#!/usr/bin/python3

# Run autogenerated tests for LLVM compiler backend:
# llvm_codegen tool generates C sources for compiling by CLANG and testing via LLVM-LIT.

import builtins
import os
import shutil
import subprocess
import sys
import multiprocessing
import math

sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
import common
from common import *

GENERATED_CODEGEN_DIR = f"{CODEGEN_DIR}/generated"

# automate running LLVM codegen tests from postrisc repo.
def main():
    with open("result.txt", "w") as outfile:
        shutil.rmtree(GENERATED_CODEGEN_DIR, ignore_errors=True)
        os.mkdir(GENERATED_CODEGEN_DIR)
        subprocess.run([os.path.expanduser("~/risc/postrisc_debug/bin/llvm_codegen")],
            cwd=GENERATED_CODEGEN_DIR, stdout=outfile, stderr=outfile, text=True, check=True)
        # print(f"LLVM_BUILD_DEBUG_BIN_DIR={LLVM_BUILD_DEBUG_BIN_DIR}")
        os.chdir(f"{LLVM_BUILD_DEBUG_BIN_DIR}")

        run_args = []
        if platform.system() == 'Windows':
            run_args = ["python3", "./llvm-lit.py"]
        else:
            run_args = ["./llvm-lit"]

        run_args.extend(["--workers", "16", "-v", GENERATED_CODEGEN_DIR])

        subprocess.run(run_args, stdout=outfile, stderr=outfile, text=True, check=True)

if __name__ == "__main__":
    main()
